-- ============================================================
-- NAM Supply Sales Dashboard — Supabase (Postgres) schema
-- Converted from MySQL dump: u476854436_nam
-- Run this FIRST in the Supabase SQL Editor, then 02_data.sql
-- ============================================================

-- ---------- RBAC ----------
CREATE TABLE roles (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        text NOT NULL UNIQUE,
  description text
);

CREATE TABLE permissions (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        text NOT NULL UNIQUE,
  description text
);

CREATE TABLE role_permissions (
  role_id       integer NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
  permission_id integer NOT NULL REFERENCES permissions(id) ON DELETE CASCADE,
  PRIMARY KEY (role_id, permission_id)
);

-- ---------- Users ----------
-- NOTE: `password` and `session_token` are carried over from the legacy
-- system for the data migration only. Once you wire up Supabase Auth,
-- add an `auth_id uuid REFERENCES auth.users(id)` column and drop these.
CREATE TABLE users (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username      text NOT NULL UNIQUE,
  password      text NOT NULL,
  full_name     text,
  role_id       integer REFERENCES roles(id),
  session_token text,
  created_at    timestamptz NOT NULL DEFAULT now()
);

-- ---------- Master data ----------
CREATE TABLE clients (
  id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_name   text NOT NULL,
  address        text,
  tin            text,
  contact_person text,
  created_at     timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE company_assignments (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_name  text UNIQUE,
  employee_name text
);

CREATE TABLE products (
  id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name           text NOT NULL,
  category_code  text,
  unit           text,
  supplier       text,
  supplier_price numeric(15,2) DEFAULT 0.00,
  nam_price      numeric(15,2) DEFAULT 0.00,
  margin         text,
  current_stock  integer DEFAULT 0,
  reorder_level  integer DEFAULT 10,
  is_draft       smallint DEFAULT 0   -- converted to boolean at end of 02_data.sql
);
CREATE INDEX idx_products_name ON products (name);

-- ---------- Transactions ----------
CREATE TABLE quotations (
  id                 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date               date NOT NULL,
  quote_ref          text,
  company            text,
  category           text,
  item               text,
  quantity_requested integer,
  suppliers_price    numeric(15,2),
  nam_unit_price     numeric(15,2),
  total_amount       numeric(15,2),
  po_number          text,
  payment_term       text,
  remarks            text,
  status             text DEFAULT 'Pending',
  created_at         timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE sales (
  id                        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date                      date NOT NULL,
  sn                        text,
  po_number                 text,
  company                   text,
  category                  text,
  item                      text,
  quantity_requested        integer,
  suppliers_price           numeric(15,2),
  total_actual_amount       numeric(15,2),
  nam_unit_price            numeric(15,2),
  total_nam_amount          numeric(15,2),
  total_nam_amount_sub_total numeric(15,2),
  income                    numeric(15,2),
  income_percent            numeric(5,2),
  date_delivered            date,
  payment_term              text,
  due_date                  date,
  payment_status            text DEFAULT 'Pending',
  date_paid                 timestamp,
  si_number                 text,
  buyer                     text,
  remarks                   text,
  supplier                  text,
  address                   text,
  tin                       text,
  sales_invoice_no          text,
  contact_person_contact    text,
  created_at                timestamptz NOT NULL DEFAULT now(),
  is_reserved               smallint DEFAULT 0,  -- converted to boolean at end of 02_data.sql
  withholding_tax           numeric(15,2) DEFAULT 0.00,
  total_amount_due          numeric(15,2) DEFAULT 0.00
);
CREATE INDEX idx_sales_date       ON sales (date);
CREATE INDEX idx_sales_company    ON sales (company);
CREATE INDEX idx_sales_category   ON sales (category);
CREATE INDEX idx_sales_created_at ON sales (created_at);

-- ---------- Audit ----------
CREATE TABLE system_logs (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     integer NOT NULL,   -- intentionally no FK: legacy logs reference deleted users
  action      text NOT NULL,
  description text,
  ip_address  text,
  created_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_system_logs_user_id ON system_logs (user_id);

-- ---------- Row Level Security ----------
-- Enable RLS on every table. Until you write real policies (see the
-- migration guide), server-side access via the service role key still works,
-- and the anon key is locked out — which is what you want by default.
ALTER TABLE roles               ENABLE ROW LEVEL SECURITY;
ALTER TABLE permissions         ENABLE ROW LEVEL SECURITY;
ALTER TABLE role_permissions    ENABLE ROW LEVEL SECURITY;
ALTER TABLE users               ENABLE ROW LEVEL SECURITY;
ALTER TABLE clients             ENABLE ROW LEVEL SECURITY;
ALTER TABLE company_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE products            ENABLE ROW LEVEL SECURITY;
ALTER TABLE quotations          ENABLE ROW LEVEL SECURITY;
ALTER TABLE sales               ENABLE ROW LEVEL SECURITY;
ALTER TABLE system_logs         ENABLE ROW LEVEL SECURITY;
