-- ============================================================
-- NAM Supply — user-managed product categories
-- Run AFTER 03_auth_rls.sql, in the Supabase SQL Editor. Safe to re-run.
--
-- The category dropdown used to be a fixed list hardcoded in the app.
-- This table makes it extensible from the Products tab ("+ New" beside
-- the Category field). The app reads it ordered by id so the legacy
-- ten keep their familiar order and new categories append below.
-- ============================================================

CREATE TABLE IF NOT EXISTS categories (
  id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       text NOT NULL UNIQUE,
  created_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE categories IS
  'Category dropdown entries. Seeded with the legacy fixed list; extended from the Products tab.';

INSERT INTO categories (name) VALUES
  ('OFFICE SUPPLIES'),
  ('CLEANING MATERIALS'),
  ('CONSUMABLES'),
  ('OFFICE TOOLS AND EQUIPMENT'),
  ('PPE'),
  ('MATERIALS'),
  ('COMPANY UNIFORM'),
  ('OFFICE FURNITURE & FIXTURES'),
  ('MEDICINE'),
  ('OTHERS')
ON CONFLICT (name) DO NOTHING;

ALTER TABLE categories ENABLE ROW LEVEL SECURITY;

-- Anyone signed in reads (dropdowns on Sales Entry, Records, Products);
-- adding/removing categories is a Products-tab action → manage_products.
DROP POLICY IF EXISTS "categories read"  ON categories;
DROP POLICY IF EXISTS "categories write" ON categories;
CREATE POLICY "categories read" ON categories FOR SELECT TO authenticated USING (true);
CREATE POLICY "categories write" ON categories FOR ALL TO authenticated
  USING ((SELECT has_permission('manage_products')))
  WITH CHECK ((SELECT has_permission('manage_products')));
